default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: notification-microservice_development

test:
  <<: *default
  database: notification-microservice_test

production:
  <<: *default
  database: notification-microservice_production
  username: notification-microservice
  password: <%= ENV['NOTIFICATION-MICROSERVICE_DATABASE_PASSWORD'] %>
